name: 'My First Work Flow'
run-name: 'My first work'
on: 
  push:
    branches:
      - main
      - features/*
runs-on: 'self hosted'
jobs:
  dhondu maharaj
  steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
       
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
     
      
    
       
  
              
          
        

